name       : onednn
version    : 2.1.2
release    : 1
source     :
    - https://github.com/oneapi-src/oneDNN/archive/refs/tags/v2.1.2.tar.gz : cca53231ec99878dc7ef3cf4984525df4691b8174e703b40dd530c50531ecea0
homepage   : https://01.org/oneDNN/
license    : 
    - Apache-2.0
    - BSD-3-Clause
component  : office.scientific
summary    : oneAPI Deep Neural Network Library (oneDNN)
description: |
    oneAPI Deep Neural Network Library (oneDNN) is an open-source cross-platform performance library of basic building blocks for deep learning applications.
avx2       : yes
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
